// Code generated by smist. DO NOT EDIT.
// you can only edit @MSIST code.
package pinfo

/*@SMIST
setIgnoreInput(true)
include("createConsts.js")
createConsts("HackerStatus", "hacker point's status", {
	HackerStatusLive : "hacker live",
	HackerStatusDead : "Hacker dead(not on line)",
	HackerStatusBan  : "hacker has been ban",
	HackerStatusReadCheckEmail : "ready to check email"
})
//.
*/
// HackerStatus hacker point's status.
type HackerStatus int

// HackerStatus's members.
const (
	// hacker live.
	HackerStatusLive = iota
	// Hacker dead(not on line).
	HackerStatusDead
	// hacker has been ban.
	HackerStatusBan
	// ready to check email.
	HackerStatusReadCheckEmail
)

// GetHackerStatusDesc get HackerStatus's desc.
func GetHackerStatusDesc(constStatus HackerStatus) string {
	switch constStatus {
	case HackerStatusLive:
		return "hacker live"
	case HackerStatusDead:
		return "Hacker dead(not on line)"
	case HackerStatusBan:
		return "hacker has been ban"
	case HackerStatusReadCheckEmail:
		return "ready to check email"
	default:
		return "?UNKNOW?"
	}
}

// GetHackerStatusName get HackerStatus's desc.
func GetHackerStatusName(constStatus HackerStatus) string {
	switch constStatus {
	case HackerStatusLive:
		return "HackerStatusLive"
	case HackerStatusDead:
		return "HackerStatusDead"
	case HackerStatusBan:
		return "HackerStatusBan"
	case HackerStatusReadCheckEmail:
		return "HackerStatusReadCheckEmail"
	default:
		return "?UNKNOW?"
	}
}
