// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.3
// source: smn_dict.proto

package smn_dict

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EDict int32

const (
	EDict_None EDict = 0
	//cc_. = 1;
	EDict_cc_HackIn    EDict = 2
	EDict_cs_HeartJump EDict = 3
	EDict_cs_Register  EDict = 4
	EDict_cs_AskHack   EDict = 5
	EDict_sc_AnsHack   EDict = 6
	EDict_ss_Search    EDict = 7
	EDict_hmsg_Message EDict = 9
)

// Enum value maps for EDict.
var (
	EDict_name = map[int32]string{
		0: "None",
		2: "cc_HackIn",
		3: "cs_HeartJump",
		4: "cs_Register",
		5: "cs_AskHack",
		6: "sc_AnsHack",
		7: "ss_Search",
		9: "hmsg_Message",
	}
	EDict_value = map[string]int32{
		"None":         0,
		"cc_HackIn":    2,
		"cs_HeartJump": 3,
		"cs_Register":  4,
		"cs_AskHack":   5,
		"sc_AnsHack":   6,
		"ss_Search":    7,
		"hmsg_Message": 9,
	}
)

func (x EDict) Enum() *EDict {
	p := new(EDict)
	*p = x
	return p
}

func (x EDict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EDict) Descriptor() protoreflect.EnumDescriptor {
	return file_smn_dict_proto_enumTypes[0].Descriptor()
}

func (EDict) Type() protoreflect.EnumType {
	return &file_smn_dict_proto_enumTypes[0]
}

func (x EDict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EDict.Descriptor instead.
func (EDict) EnumDescriptor() ([]byte, []int) {
	return file_smn_dict_proto_rawDescGZIP(), []int{0}
}

var File_smn_dict_proto protoreflect.FileDescriptor

var file_smn_dict_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x6d, 0x6e, 0x5f, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x73, 0x6d, 0x6e, 0x5f, 0x64, 0x69, 0x63, 0x74, 0x2a, 0x84, 0x01, 0x0a, 0x05, 0x45,
	0x44, 0x69, 0x63, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x63, 0x63, 0x5f, 0x48, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x10, 0x02, 0x12, 0x10, 0x0a,
	0x0c, 0x63, 0x73, 0x5f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x4a, 0x75, 0x6d, 0x70, 0x10, 0x03, 0x12,
	0x0f, 0x0a, 0x0b, 0x63, 0x73, 0x5f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x04,
	0x12, 0x0e, 0x0a, 0x0a, 0x63, 0x73, 0x5f, 0x41, 0x73, 0x6b, 0x48, 0x61, 0x63, 0x6b, 0x10, 0x05,
	0x12, 0x0e, 0x0a, 0x0a, 0x73, 0x63, 0x5f, 0x41, 0x6e, 0x73, 0x48, 0x61, 0x63, 0x6b, 0x10, 0x06,
	0x12, 0x0d, 0x0a, 0x09, 0x73, 0x73, 0x5f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x10, 0x07, 0x12,
	0x10, 0x0a, 0x0c, 0x68, 0x6d, 0x73, 0x67, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10,
	0x09, 0x42, 0x45, 0x0a, 0x02, 0x70, 0x62, 0x42, 0x08, 0x73, 0x6d, 0x6e, 0x5f, 0x64, 0x69, 0x63,
	0x74, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x73, 0x47, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x2f, 0x68, 0x61, 0x63, 0x6b,
	0x6e, 0x65, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x6d, 0x6e, 0x5f, 0x64, 0x69, 0x63, 0x74, 0x3b,
	0x73, 0x6d, 0x6e, 0x5f, 0x64, 0x69, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smn_dict_proto_rawDescOnce sync.Once
	file_smn_dict_proto_rawDescData = file_smn_dict_proto_rawDesc
)

func file_smn_dict_proto_rawDescGZIP() []byte {
	file_smn_dict_proto_rawDescOnce.Do(func() {
		file_smn_dict_proto_rawDescData = protoimpl.X.CompressGZIP(file_smn_dict_proto_rawDescData)
	})
	return file_smn_dict_proto_rawDescData
}

var file_smn_dict_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_smn_dict_proto_goTypes = []interface{}{
	(EDict)(0), // 0: smn_dict.EDict
}
var file_smn_dict_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smn_dict_proto_init() }
func file_smn_dict_proto_init() {
	if File_smn_dict_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smn_dict_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smn_dict_proto_goTypes,
		DependencyIndexes: file_smn_dict_proto_depIdxs,
		EnumInfos:         file_smn_dict_proto_enumTypes,
	}.Build()
	File_smn_dict_proto = out.File
	file_smn_dict_proto_rawDesc = nil
	file_smn_dict_proto_goTypes = nil
	file_smn_dict_proto_depIdxs = nil
}
