// Code generated by smist. DO NOT EDIT.
package hacknetitf

import (
	"net"

	"github.com/ProtossGenius/hacknet/pb/hnp"
	"google.golang.org/protobuf/proto"
)

/*@SMIST
setIgnoreInput(true);
include('parseProtos.js');
proto2Client("./protos/hnp.proto")
*/
// Pack_hnp_Register pack message hnp_Register.
func Pack_hnp_Register(email string, msg *hnp.Register) (resp *hmsg.Message, err error) {
	var any *anypb.Any
	if any, err = ptypes.MarshalAny(msg); err != nil {
		return nil, err
	}

	return &hmsg.Message{Email: email, Enum: int32(smn_dict.EDict_hnp_Register), Msg : any}, nil
}

// Pack_hnp_Result pack message hnp_Result.
func Pack_hnp_Result(email string, msg *hnp.Result) (resp *hmsg.Message, err error) {
	var any *anypb.Any
	if any, err = ptypes.MarshalAny(msg); err != nil {
		return nil, err
	}

	return &hmsg.Message{Email: email, Enum: int32(smn_dict.EDict_hnp_Result), Msg : any}, nil
}

// Pack_hnp_CheckEmail pack message hnp_CheckEmail.
func Pack_hnp_CheckEmail(email string, msg *hnp.CheckEmail) (resp *hmsg.Message, err error) {
	var any *anypb.Any
	if any, err = ptypes.MarshalAny(msg); err != nil {
		return nil, err
	}

	return &hmsg.Message{Email: email, Enum: int32(smn_dict.EDict_hnp_CheckEmail), Msg : any}, nil
}

// Pack_hnp_Forward pack message hnp_Forward.
func Pack_hnp_Forward(email string, msg *hnp.Forward) (resp *hmsg.Message, err error) {
	var any *anypb.Any
	if any, err = ptypes.MarshalAny(msg); err != nil {
		return nil, err
	}

	return &hmsg.Message{Email: email, Enum: int32(smn_dict.EDict_hnp_Forward), Msg : any}, nil
}

// Pack_hnp_ForwardMsg pack message hnp_ForwardMsg.
func Pack_hnp_ForwardMsg(email string, msg *hnp.ForwardMsg) (resp *hmsg.Message, err error) {
	var any *anypb.Any
	if any, err = ptypes.MarshalAny(msg); err != nil {
		return nil, err
	}

	return &hmsg.Message{Email: email, Enum: int32(smn_dict.EDict_hnp_ForwardMsg), Msg : any}, nil
}

// Pack_hnp_HeartJump pack message hnp_HeartJump.
func Pack_hnp_HeartJump(email string, msg *hnp.HeartJump) (resp *hmsg.Message, err error) {
	var any *anypb.Any
	if any, err = ptypes.MarshalAny(msg); err != nil {
		return nil, err
	}

	return &hmsg.Message{Email: email, Enum: int32(smn_dict.EDict_hnp_HeartJump), Msg : any}, nil
}

